Use gcc --sysroot in rap stage3 post glibc install
gentoo/prefix pull request #22
Opened 2023-03-01 17:44 UTC by bartoldeman

Since glibc now has non-prefixed filenames in
`$EPREFIX/usr/lib64/libc.so`, it picks up non-prefixed `/lib64/libc.so.6` from stage2 gcc, unless we replace its -I, -L, and -B options by --sysroot. Then it will look at the same places as the future stage3 gcc.

This avoids issues building binutils, which can't find dlopen in older `/lib64/libc.so.6`, since dlopen used to be in `libdl` instead.

The whole logic no longer tests for compiler == gcc, since clang is only used for non-rap on MacOS.

2023-03-02 09:36 UTC, chewi requested changes
Looks great, thanks! Just one minor thing, gcc documents the `--sysroot` option as being `--sysroot=dir` so please add the `=`. That's how I've always used it.

Now I understand why I didn't see this issue when testing. I was bootstrapping on top of Gentoo, and my host libc matched the prefix libc, so it didn't break. When I tested cross-compiling, I didn't use bootstrap-prefix.sh, but used cross-boss, which already adds `--sysroot` to the flags.

2023-03-02 13:26 UTC, bartoldeman commented
Thanks for the feedback, I added the =. Funnily enough GCC docs have `--sysroot=` but `--isysroot` without the `=`.

There's another issue in the bootstrap much later with `dev-libs/libgcrypt` when bootstrapping on a CentOS7 kernel, which can be fixed by setting the `-getentropy` USE flag. I'm waiting for my bootstrap to finish, and will then submit a PR about that too.

2023-03-02 13:32 UTC, chewi approved these changes

2023-03-03 00:55 UTC, zigford commented
With this patch, I was finally able to run gentoo-prefix on RedHat 8. Thanks

2023-03-03 03:47 UTC, bartoldeman commented
I submitted the getentropy fix as
https://github.com/gentoo/gentoo/pull/29906

2023-03-03 11:28 UTC, APN-Pucky commented
Debian 11 works with this too.

2023-03-04 02:21 UTC, closed without merging

2023-03-04 02:21 UTC, thesamesam commented
Many thanks for this!